baseURL = "https://sacredchao.tk/"
languageCode = "ru-ru"
title = "Sacredchao"
relativeURLS=true
DefaultContentLanguage = "ru"
theme = "anatole"
summarylength = 50
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = ""

[params]
title = "Sacredchao"
author = "Sacredchao"
description = ""
profilePicture = "images/profile.png"
keywords = ""
favicon = "favicons/favicon.ico"
displayMode = "light"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
# Google Site Verification
#googleSiteVerify = ""

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
## [[params.socialIcons]]
## icon = "fa-rss-square"
## title = "RSS"
## url = "index.xml"

## Menu items

[menu]

  [[menu.main]]
  name = "Главная"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Архив"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Что это?"
  weight = 300
  identifier = "about"
  url = "/about/"
  
  [[menu.main]]
  name = "RSS"
  weight = 400
  identifier = "RSS"
  url = "/index.xml"
