baseURL = "https://sacredchao.tk"
languageCode = "ru-ru"
defaultContentLanguage = "ru"
title = "Sacredchao"
theme = "tale"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "sacredchao"

[params]
   author = "sacredchao"
   description = "Anubis is a simple minimalist theme for Hugo blog engine."
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "light"
   readMore = true
   
[languages.ru]
  languageName = "Russian"   

[menu]

  [[menu.main]]
    identifier = "about"
    name = "Что это?"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Архив"
    identifier = "archive"
    url = "/posts/"
    weight = 2
	
 [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 3	

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true