baseURL: 'https://sacredchao.tk'
title: Sacredchao
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Sacredchao
  description: 'Nothing ever ends'
  author: Me
  # author: ["Me", "You"] # multiple authors

  images: "<link or path of image for opengraph, twitter-cards>"

  ShowReadingTime: false
  ShowShareButtons: true
  comments: false
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  assets:
    favicon: '<path / external url>'

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  socialIcons:
    - name: twitter
      url: '#'