baseURL = "https://sacredchao.tk"
languageCode = "ru-ru"
title = "Sacredchao"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 10 # Set the number of posts to show before overflowing to the next page.
summaryLength = 50 # Configure how long the post summary should be on the homepage.

[taxonomies]
  tag = "tags"
  categories = "categories"
  
[author]
  name = "sacredchao"

[params]
 	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "Nothing ever ends"
    showReadMore = true
   
[[menu.main]]
	identifier = "about"
	name = "Что это?"
	url = "/about/"
	weight = 1

[[menu.main]]
	identifier = "archive"
	name = "Архив"
	url = "/post/"
	weight = 2

[[menu.main]]
	name = "RSS"
	identifier = "rss"
	url = "/index.xml"
	weight = 3

