languageCode: "ru-ru"
defaultContentLanguage: "ru"
baseUrl: "/"
title: "3/I0"
theme: "anubis"
paginate: 10
disqusShortname: ""
googleAnalytics: ""
enableRobotsTXT: true
relativeURLS: true

menu:
  main:
  - identifier: stories
    name: рассказки
    title: рассказки
    url: /categories/рассказки/
    weight: 10
  - identifier: short
    name: культяпки
    title: культяпки
    url: /categories/культяпки/
    weight: 20
  - identifier: archive
    name: свалка
    title: свалка
    url: /posts/
    weight: 30

params:
  author: "3/I0"
  email:  # used for microformats
  avatar: "/images/doc.jpeg" # used for microformats  
  description: "Посевы неразумного"
  # Uncomment if you need this
  images:
     - images/og-featured.jpg # relative path to "static" directory
  customCSS:
     - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "02.01.2006"
  paginationSinglePost: true
  style: dark
  readMore: true # show read more button
  readNextPosts: 0  # show 5 related posts, 0 by default
  disableSummary: false
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  social:
#    - id: telegram
#      name: ok310
    - id: twitter
      url: "https://twitter.com/ok3I0"
      icon: "twitter"
    - id: telegram
      url: "https://t.me/ok310"
      icon: "telegram"
  webmentions:
#    url: https://webmention.io/ok310.gq/webmention
    login: ok310.gq
    pingback: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
