languageCode: "ru-ru"
defaultContentLanguage: "ru"
baseUrl: ""
title: "310"
theme: "anubis"
paginate: 10
disqusShortname: ""
googleAnalytics: ""
enableRobotsTXT: true
relativeURLS: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "310"
  email:  # used for microformats
  avatar: "/images/doc.jpeg" # used for microformats
  favicon: "/images/favicon.ico"
  description: "Посевы неразумного"
  # Uncomment if you need this
  images:
     - images/og-featured.png # relative path to "static" directory
  customCSS:
     - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "02.01.2006"
  paginationSinglePost: true
  style: dark
  readMore: true # show read more button
  readNextPosts: 0  # show 5 related posts, 0 by default
  disableSummary: false
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
